### ISSUE TITLE
error in spark.createNavigator

### ISSUE THREAD

**Issue by fabriziogiordano** [csotiriou/spark-navigator#1]
How to repro:
- clone repo
- `cd example`
- `npm install`
- `react-native run-ios`

![simulator screen shot nov 27 2016 4 56 37 pm](https://cloud.githubusercontent.com/assets/109390/20652151/c7ad2d90-b4c1-11e6-8770-6c8ff7b6a107.png)

**Comment by EricCarrGH** [comment]
To get the example to run, in example/navigators/main.js, I change this line:

`const MainSpark = spark.createNavigator((routeName) => {`

to this:

`const MainSpark = spark.createSpark((routeName) => {`

It seems "createNavigator" was renamed to "createSpark."

Christos, can you confirm? :)

**Comment by heliosPortal** [comment]
@EricCarrGH - thanks.  It's amazing how long you can look at a piece of code searching for a bug when it is right under your nose.  It worked for me.  Now, off to create some bugs of my own...

**Comment by csotiriou** [comment]
@EricCarrGH @heliosPortal The most amazing thing is how long can an issue stay alive without being taken care of by the responsible person (me, in this instance.).

Sorry about this, guys, real-life took over. Since the spark navigator is obsolete (and useless, I might add), I believe I can close this. And this repo, too.
